### ISSUE TITLE
Can not found the link 'https://github.com/cambridgeltl/uniprotidmap.git'

### ISSUE THREAD

**Issue by Lilysc** [spyysalo/pubtator#10]
Hi:
  I read your paper 'LION LBD: a literature-based discovery system for cancer biology' published in Bioinformatics, but I could not find the link 'https://github.com/cambridgeltl/uniprotidmap.git' mentioned in README file, Will these part of source code be released ?Thanks!

**Comment by spyysalo** [comment]
Hi @Lilysc,

Thank you for letting me know of this oversight! I'm no longer at Cambridge but I have contacted the person who administers this repository and asked them to fix the settings.
