### ISSUE TITLE
Parsing fails when some entity identifiers are missing

### ISSUE THREAD

**Issue by littlewine** [spyysalo/pubtator#9]
Hi,

I am trying to use this tool to convert some annotated documents (PubMed format) to BRAT (standoff) format, taken directly from the NCBI api (such as [this](https://www.ncbi.nlm.nih.gov/CBBresearch/Lu/Demo/RESTful/tmTool.cgi/BioConcept/23211523/PubTator/)).
However, the following issue arises:
Usually, there is an identifier (such as MESH identifier etc) next to the entity type, seperated by a tab (\t). When some of the identifiers are missing in one of the specific documents, the conversion fails because the tool cannot read and process this document id.

Specifically, I am getting the following error:
`WARNING:root:Error reading NCBI_downloaded.txt: line 5551: 23211523	0	9	b-catenin	Gene
 (skipping...)`

Those identifiers end up as notes in the BRAT standoff format.
Is there a proper way to overcome this error (either by skipping the notes of missing entities, or dropping all the identifiers altogether)?

Thanks

**Comment by littlewine** [comment]
The problem was that some lines (corresponding to entities with no identifier) were missing a tab.
To fix that, you can simply replace the [matching regex for spans/entities](https://github.com/spyysalo/pubtator/blob/14dee4508241228f6a45119c7f18f51f24d37657/pubtator.py#L17) in pubtator/pubtator.py with this line:

`SPAN_RE = re.compile(r'^(\d+)\t(\d+)\t(\d+)\t([^\t]+)\t(\S+)\t*(\S*)(?:\t(.*))?\s*$')`

I can confirm that this solves the problem with reading the annotation files from the pubmed format and hence works fine for the conversion to standoff.

**Comment by spyysalo** [comment]
@littlewine badly belated thanks!
